IMAGE_NAME = "centos/stream8"
N = 2
ANSIBLE_NODE = true
ANSIBLE_IMAGE = "centos/7"

Vagrant.configure("2") do |config|

	config.vm.provider "libvirt" do |v|
    v.memory = 1024
    v.cpus = 2
	end
      
	config.vm.define "k8s-master.cluster.local" do |master|
    master.vm.box = IMAGE_NAME
		master.vm.network "private_network", ip: "192.168.50.10"
		master.vm.hostname = "k8s-master.cluster.local"
  end

	(1..N).each do |i|
		config.vm.define "node-#{i}.cluster.local" do |node|
      node.vm.box = IMAGE_NAME
      node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
			node.vm.hostname = "node-#{i}.cluster.local"
    end
  end

	if ANSIBLE_NODE == true
		config.vm.define "ansible.cluster.local" do |node|
			node.vm.box = ANSIBLE_IMAGE
			node.vm.network "private_network", ip: "192.168.50.5"
			node.vm.hostname = "ansible.cluster.local"
		end
	end

end
